DROP SCHEMA IF EXISTS SOKOSHOP;
CREATE SCHEMA SOKOSHOP;
USE SOKOSHOP;

CREATE TABLE PRODUCT(
    ID INT PRIMARY KEY,-- 2 
    FNAME VARCHAR(100),
    PRICE BIGINT,
    NUM INT,
    FUNDS INT,
    IMAGE_URL TEXT,
    DESCRIPTION TEXT
);

CREATE TABLE ORDER{
    ID INT PRIMARY KEY,
    DTIME DATE,
    TOTAL BIGINT
};

CREATE TABLE PRODUCT_IN_ORDER(
  PID INT,
  ORDER_ID INT,
  QUANTITY INT,
  NOTE TEXT,
  PRIMARY KEY(PID, ORDER_ID),
  FOREIGN KEY (PID) REFERENCES PRODUCT(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRODUCT_CATEGORY(
  PID INT ,
  CATEGORY VARCHAR(100),
  PRIMARY KEY(PID, CATEGORY),
  FOREIGN KEY (PID) REFERENCES PRODUCT(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CUSTOMMER{
  ID PRIMARY,
  FULLNAME TEXT,
  SDT TEXT,
  COMMENT TEXT -- link file
}

CREATE TABLE COST(
    ID INT PRIMARY,
    DTIME DATE,
    CATEGORY VARCHAR(100),
    PRICE INT,
    QUANTITY INT
);
-------------------------------------------------------------------------------------------------
