-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 10, 2021 at 06:45 PM
-- Server version: 8.0.26
-- PHP Version: 7.4.23
DROP SCHEMA IF EXISTS `SOKOSHOP`;
CREATE SCHEMA `SOKOSHOP`;
USE `SOKOSHOP`;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- --------------------------------------------------------

CREATE TABLE `cost` (
  `ID` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `DTIME` date DEFAULT NULL,
  `CATEGORY` varchar(100) DEFAULT NULL,
  `PRICE` int DEFAULT NULL,
  `QUANTITY` int DEFAULT NULL
);

-- --------------------------------------------------------
CREATE TABLE `order` (
  `ID_ORDER` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `DTIME` date DEFAULT NULL,
  `TOTAL` int DEFAULT 0,
  `STATE` tinyint(1)  NULL,
  `LINKBILL` text default NULL,
  `COMPLETED` tinyint(1) DEFAULT 1
);

-- --------------------------------------------------------
CREATE TABLE `customer` (
  `ID` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `FULLNAME` text,
  `PHONE_NO` CHAR(10),
  `COMMENT` text,
  `NUMANDSTREET` text,
  `DISTRICT` text,  
  `ID_ORDER` int,
  FOREIGN KEY (`ID_ORDER`) REFERENCES `order` (`ID_ORDER`)
);

-- --------------------------------------------------------
CREATE TABLE `product` (
  `PID` char(5) NOT NULL PRIMARY KEY,
  `PRO_NAME` varchar(100)  NULL,
  `PRICE` int  NULL,
  `QUANTITY` int  NULL,
  `FUND` int  NULL,
  `IMAGE_URL` text,
  `TITLE` text,
  `DESCR` text,
  `CAT_NAME` varchar(100) NOT NULL,
  `TOP_PRO` tinyint(1)  NULL
);

-- --------------------------------------------------------
CREATE TABLE `product_in_order` (
  `ID` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `PID` char(5) NOT NULL,
  `ID_ORDER` int NOT NULL,
  `QUANTITY` int DEFAULT NULL,
  `NOTE` text,
  `TOTAL` int DEFAULT 0,
  -- FOREIGN KEY (`PID`) REFERENCES `product` (`PID`),
  FOREIGN KEY (`ID_ORDER`) REFERENCES `order` (`ID_ORDER`)
);


INSERT INTO `product` (`PID`, `PRO_NAME`, `PRICE`, `QUANTITY`, `FUND`, `IMAGE_URL`, `TITLE`, `DESCR`, `CAT_NAME`, `TOP_PRO`) VALUES
('pro01', 'Cà Phê Sữa Đá', 29000, 50, 10000, '../IMAGE/CaPheSuaDa.jpg', 'Cà phê sữa đá - Sự độc đáo trong thưởng thức cà phê của người Việt ', 'Cà phê phin kết hợp cùng sữa đặc là một sáng tạo đầy tự hào của người Việt, được xem món uống thương hiệu của Việt Nam.\r\n\r\nKhi người Pháp đem văn hóa cà phê vào Việt Nam, người bản xứ thay thế sữa tươi đắt đỏ bằng sữa đặc rẻ tiền hơn để pha cùng cà phê. Tuy nhiên, bằng sự kết hợp hài hòa giữa các thái cực đắng – ngọt, bùi – béo, ly cà phê sữa đá lại sánh đặc và đậm đà hơn, không làm mất đi công dụng của cà phê mà bổ sung thêm năng lượng cho cơ thể từ sữa đã trở thành quen thuộc với nếp sống của người Việt và là một nét sáng tạo riêng, chinh phục được trái tim hàng triệu người yêu cà phê trên thế giới.\r\n\r\nNhà báo Nicola Graydon từng miêu tả và chia sẻ cảm nhận của mình trên tờ nhật báo nổi tiếng của Anh rằng: \"Đó là loại cà phê mạnh, nhỏ giọt từ một phin kim loại nhỏ, bên dưới ly chứa khoảng ¼ lượng sữa đặc. Sau khoảng 15 phút, khi café ngừng nhỏ giọt, bạn sẽ khuấy đều và cho đá vào. Đầu tiên, tôi không chịu được cái ngọt kiểu như vậy. Tuy nhiên sau 3 ngày, tôi bị khuất phục và nghiện cái ngọt “thần thánh” ấy. Thật tuyệt vời khi cảm nhận cái ngọt thanh mát trong cuống họng, điều mà chúng ta không thấy ở một ly latte cổ điển”.\r\n\r\nCũng có người đã miêu tả Cà phê sữa đá rằng: Cà phê thì đắng mà sữa lại quá ngọt ngào. Hai vị đắng - ngọt như hương vị của cuộc sống, nên thưởng thức Cà phê sữa cũng giống như đang thưởng thức cuộc sống.', 'Cà Phê', 1),
('pro02', 'Bạc Sỉu', 29000, 20, 10000, '../IMAGE/BacSiu.jpg', 'Bạc sỉu – Nét văn hóa đầy tự hào của người Sài Gòn', 'Theo chân những người gốc Hoa đến định cư tại Sài Gòn, Bạc sỉu là cách gọi tắt của \"Bạc tẩy sỉu phé\" trong tiếng Quảng Đông. Bạc là \"trắng\". Tẩy là \"ly\". Sỉu là \"một chút\". Phé là \"cà phê\".\r\n\r\nBạc sỉu chính là \"Ly sữa trắng kèm một chút cà phê\".\r\n\r\nNgười lao động phổ thông khi xưa dùng sữa đặc pha với nước nóng để thay thế cho sữa tươi đắt đỏ trong thời điểm ấy. Tuy vậy, vị sữa đặc pha khá nồng, nên họ biến tấu chút cà phê vào cho ly sữa thêm thơm và hấp dẫn.\r\n\r\nNgười Sài Gòn \"chánh hiệu con mèo đen\" dùng Bạc sỉu nóng. Theo thời gian, người ta thêm đá vào ly “sữa cà phê” này để thưởng thức được cả trong những ngày oi bức.\r\n\r\nQua đôi bàn tay “tài hoa” của các nghệ nhân pha chế, Bạc sỉu của Nhà lại mang hương vị rất riêng và rất khác so với những nơi khác. Tại đây, mỗi ly Bạc sỉu được tạo nên từ tinh chất cà phê thượng hạng, sữa thơm béo và kỹ thuật pha chế điêu luyện sẽ mang đến cho bạn một hương vị bạc sỉu hoàn toàn mới.\r\n\r\nBởi vì thức uống này có thành phần chính là sữa thêm chút cà phê thơm lừng nên vừa giúp bạn thỏa mãn về vị giác và giúp tỉnh táo để bạn có một ngày học tập và làm việc ngập tràn năng lượng. Thức uống này rất phù hợp những ai vừa muốn trải nghiệm chút vị đắng của cà phê vừa muốn thưởng thức vị ngọt béo ngậy từ sữa.\r\n\r\nNgoài ra, ly Bạc sỉu thơm ngon cũng giúp cho những cuộc gặp gỡ nhau thêm thân tình, những câu chuyện sẻ chia trở nên trọn vẹn.', 'Cà Phê', 0),
('pro03', 'Cà Phê Đen Đá', 29000, 30, 10000, '../IMAGE/CaPheDenDa.jpg', 'Cà phê đen - Phong vị trầm lắng hảo hạng', 'Một tách cà phê thơm ngào ngạt, phảng phất mùi cacao là món quà tự thưởng tuyệt vời nhất cho những ai mê đắm tinh chất nguyên bản nhất của cà phê.\r\n\r\nNgười ta thường nói “Chẳng thể nào vội vàng khi thưởng thức một tách Cà phê đen” nên thường phải ngồi rất lâu mới cảm nhận hương thơm nồng đậm và  vị đắng mượt mà của cà phê làm bừng tỉnh mọi giác quan trên cơ thể.\r\n\r\nCó nhiều cách để cho ra một ly cà phê, tùy theo cách chế biến ở mỗi nơi mà hương vị khi uống cũng khác nhau. Tại Sokoshop, từng hạt cà phê đều trải qua những “thử thách” chặt chẽ về chất lượng gieo trồng, vun dưỡng để chắt lọc ra những giọt cà phê tinh chất và nguyên bản nhất. Và từ đó, Cà phê đen Sokoshop lại mang một hương vị rất riêng biệt và bạn không thể tìm thấy ở một nơi khác.\r\n\r\nNhững ai trót mê đắm thức uống này thường nói với nhau rằng, dù cuộc sống hối hả đến đâu, bao giờ cũng đủ thời gian cho một tách Cà phê đen.\r\n\r\nVậy thì còn chần chờ gì mà không gọi cho mình một tách cà phê trầm lắng, thi vị giữa dòng đời vồn vã.', 'Cà Phê', 0),
('pro04', 'Caramel Macchiato Đá', 50000, 15, 20000, '../IMAGE/CaramelMacchiatoDa.jpg', 'Caramel Macchiato - Cái nhấp môi ngọt ngào', 'Mỗi cái nhấp môi vào tách Caramel Macchiato sẽ đem đến một sự ngạc nhiên thú vị, vì nhiều hương vị được gói gọn trong một tách cà phê.\r\n\r\nNhững năm trở lại đây, những món đồ uống liên quan đến cụm từ “Macchiato” đều trở thành trào lưu của các tín đồ sành ăn.\r\n\r\nTùy vào sở thích, tâm trạng khác nhau mà chúng ta có những cảm nhận rất riêng. Ở Sokoshop, Caramel Macchiato là một trong món khách hàng ưa thích chọn lựa.\r\n\r\nVậy điều gì đã làm nên thức uống đầy mê hoặc này?\r\n\r\nĐể tạo nên một tách cà phê Caramel Macchiato tuyệt hảo thì yêu cầu bắt buộc phải sử dụng cà phê thượng hạng và nguyên chất. Do đó, Sokoshop luôn đảm bảo chất lượng cà phê từ chọn giống, chăm sóc, sơ chế,… để mang đến cho thực khách sự ngạc nhiên và thỏa mãn vị giác bởi một tách cà phê Caramel Macchiato thơm béo của bọt sữa sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.\r\n\r\nBên cạnh đó, bằng sự điêu luyện và tỉ mỉ của các nghệ nhân pha chế, mỗi tách Caramel Macchiato tại Sokoshop đều thể hiện sự tinh tế, nhẹ nhàng mang đến cảm xúc thăng hoa cho người thưởng thức.\r\n\r\nGiờ thì thử liền một tách Caramel Macchiato ngon đúng điệu đi chứ nhỉ!', 'Cà Phê', 0),
('pro05', 'Latte Nóng', 50000, 30, 20000, '../IMAGE/LatteNong.jpg', 'Latte - Sự tinh tế trong hương vị, mùi vị lẫn nhãn quan', 'Khi chuẩn bị Latte, cà phê Espresso và sữa nóng được trộn lẫn vào nhau, bên trên vẫn là lớp bọt sữa nhưng mỏng và nhẹ hơn Cappucinno.\r\n\r\nGiống như Cappuchino, Latte cũng được pha chế gồm 3 lớp nguyên liệu chính: Cà phê Espresso, sữa nóng và lớp bọt sữa thơm mịn. Nếu không phải là người sành thưởng thức cà phê, bạn sẽ khó lòng phân biệt được 2 loại cà phê này. Khi pha chế Latte, các Barista thường thể hiện sự sáng tạo hoặc gửi gắm tâm ý của họ đến thực khách thông qua những hình vẽ nghệ thuật và tinh tế. Thực chất, điểm khác biệt giữa Latte và Cappuchino chính là: Lượng bọt sữa của Cappuchino dày hơn so với Latte.\r\n\r\nNgoài ra, Cà phê Latte Sokoshop là một sự kết hợp tinh tế giữa vị đắng cà phê Espresso nguyên chất hòa quyện cùng vị sữa nóng ngọt ngào, bên trên là một lớp kem mỏng nhẹ tạo nên một tách cà phê hoàn hảo về hương vị lẫn nhãn quan.\r\n\r\nChọn một tách Latte tinh tế chính là cách giúp bạn có một ngày thêm trọn vẹn, thử ngay nhé!', 'Cà Phê', 1),
('pro06', 'Americano Nóng', 40000, 20, 15000, '../IMAGE/AmericanoNong.jpg', 'Khám phá tách cà phê Americano theo phong cách Mỹ', 'Americano bắt nguồn từ Espresso. Đây là một thức uống truyền thống của Mỹ và đã trở nên quen thuộc với các tín đồ cà phê trên thế giới.\r\n\r\nCâu chuyện được kể lại rằng trong Thế Chiến Thứ II, những binh sĩ Mỹ đóng quân trên đất Ý đã rơi vào tình trạng \"say bí tỉ\" khi lần đầu tiếp xúc với hương vị Espresso mạnh mẽ vùng bản địa.\r\n\r\nVốn không quen với độ sánh đặc của cà phê nơi đây, họ đã nảy ra ý tưởng thêm nước nóng vào cốc Espresso để làm loãng nó.\r\n\r\nVà từ đó, Americano của người Mỹ (American) ra đời.\r\n\r\nTại Sokoshop, Americano được các nghệ nhân pha chế bằng cách pha thêm nước với tỷ lệ nhất định vào tách cà phê Espresso, từ đó mang lại hương vị nhẹ nhàng và giữ trọn được mùi hương cà phê đặc trưng.\r\n\r\nLợi ích khi thưởng thức cà phê Americano mỗi ngày\r\n\r\nNgoài việc mang đến sự tỉnh táo, linh hoạt cho người uống, Americano còn có thành phần chống oxy hóa nên nếu thưởng thức hằng ngày sẽ giúp ngăn ngừa xơ gan, giảm hen suyễn, lợi tiểu và hỗ trợ chống ung thư.', 'Cà Phê', 0),
('pro07', 'Cappuccino Nóng', 50000, 40, 20000, '../IMAGE/CappuccinoNong.jpg', 'Cappuccino - Hương vị hoàn hảo làm say đắm mọi giác quan', 'Cappuccino là một thức uống quen thuộc gắn liền với đất nước Ý xinh đẹp và thơ mộng. \r\n\r\nĐây là một loại thức uống được pha chế cầu kỳ và tinh tế. Một tách Cappuccino ngon đúng điệu là sẽ mang hương vị nồng nàn của cà phê Espresso hòa quyện sữa thơm dịu, đi kèm lớp bọt sữa bồng bềnh, béo ngậy.\r\n\r\nBởi chính hương vị thơm ngon cùng nghệ thuật pha chế và tạo hình bọt sữa đầy tinh tế của Barista tại Sokoshop, khi nhấp một ngụm Cappuccino, thực khách sẽ được trải nghiệm một hành trình vị giác đầy mê hoặc. Đó cũng là lý do vì sao Cà phê Cappuccino dễ dàng chinh phục nhiều khách hàng trong những năm qua.\r\n\r\nHãy đặt thử và cho Sokoshop cảm nhận của riêng mình nhé!', 'Cà Phê', 1),
('pro08', 'Espresso Nóng', 40000, 20, 15000, '../IMAGE/EspressoNong.jpg', 'Espresso - Cà phê tinh chất nhất theo phong cách Ý', 'Tạm gác lại những ồn ào nơi phố thị và thử nhâm nhi ly cà phê Espresso hương vị đậm đà, tinh tế của Sokoshop để tận hưởng những khoảnh khắc diệu kỳ của cuộc sống.\r\n\r\nNgười ta vẫn hay ví Espresso là phép màu trong một chiếc tách vì độ quyến rũ không phai của nó.\r\n\r\nMột cốc Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng, phối trộn với tỉ lệ cân đối hạt Robusta, cho ra vị ngọt caramel, vị chua dịu và sánh đặc. Để đạt được sự kết hợp này, Sokoshop xay tươi hạt cà phê cho mỗi lần pha.\r\n\r\nLớp bọt khí nhỏ li ti màu nâu nhạt nằm trên cùng của cốc Espresso được gọi là crema. Thời gian để \"bắt\" được lớp crema xốp nhẹ và lâu tan chỉ vỏn vẹn 27 giây, dưới áp suất nước xấp xỉ 9 bar của Macchiana (máy pha Espresso) với nhiệt độ không quá 95°C. Nếu không chính xác, crema của bạn sẽ bị đắng.\r\n\r\nTuy nhiên, không có gì gọi là chuẩn mực, cà phê Espresso cũng thế. Hương vị cuối cùng của Espresso được tạo ra bằng dấu ấn của Barista khi pha chế.\r\n\r\nVì thế mỗi cốc Espresso Sokoshop mang đến cho bạn đều mang một vị ngon rất riêng, không trộn lẫn, không lặp lại.', 'Cà Phê', 0),
('pro09', 'Mocha Đá', 50000, 10, 20000, '../IMAGE/MochaDa.jpg', 'Mocha – Một chút đắng của tình yêu đầu', 'Không như cà phê Cappuccino chỉ có một lớp bọt sữa trên bề mặt, cà phê Mocha còn hòa quyện cả vị thơm béo của kem tươi và sốt sô-cô-la.\r\n\r\nNgười ta thường ví cà phê như một thức uống kỳ diệu. Chúng không ngọt ngào để nuông chiều cảm xúc của bất kỳ ai nhưng lại mang đến một sự bí ẩn rất cuốn hút, khơi gợi người khác phải khám phá.\r\n\r\nBên cạnh những loại cà phê máy như Espresso, Cappuccino, Latte,… thực khách tại Sokoshop cũng dành nhiều tình cảm cho một loại cà phê khác mang tên Mocha. Mocha là một dạng hỗn hợp giữa cà phê và sô-cô-la nóng. Không như cà phê Cappuchino chỉ có một lớp bọt sữa trên bề mặt, cà phê Mocha còn hòa quyện cả vị thơm béo của kem tươi và sốt sô-cô-la. Mùi vị này, hương thơm này tựa như hương vị của một tình yêu chớm nở, vừa có chút vị đắng của Espresso và sự ngọt ngào đầy lôi cuốn.\r\n\r\n Nếu bạn thích socola và cũng nghiện cà phê thì Mocha sẽ là sự lựa chọn hoàn hảo rồi đấy!', 'Cà Phê', 0),
('pro10', 'Cold Brew Truyền Thống', 45000, 10, 18000, '../IMAGE/ColdBrewTruyenThong.jpg', 'Cold Brew – Cách thưởng thức cà phê theo phong cách mới', 'Những năm trở lại đây, cà phê pha lạnh Cold Brew đã trở thành một xu hướng thưởng thức mới đối với các tín đồ cà phê Việt Nam, đang dần trở nên phổ biến rộng rãi, được giới văn phòng và các bạn trẻ vô cùng yêu thích.\r\n\r\nTại Sokoshop, Cold Brew được ủ và phục vụ mỗi ngày từ 100% hạt Arabica Cầu Đất với hương gỗ thông, hạt dẻ, nốt sô-cô-la đặc trưng, thoang thoảng hương khói nhẹ giúp Cold Brew giữ nguyên vị tươi mới.\r\n\r\nKhông dừng lại ở đó, Cold Brew là một phiên bản nâng cấp hơn về chất lượng của hương vị. Cách pha chế Cold Brew tưởng chừng như đơn giản nhưng thực chất lại đòi hỏi rất nhiều sự tinh tế, cẩn trọng của người barista trong từng khâu thực hiện.\r\n\r\nMất 24 tiếng để ngâm ủ cà phê trong nước lạnh, Cold Brew mang đến sự mượt mà và tinh tế trong hương vị.\r\n\r\nCà phê Cold Brew được đánh giá là ngon nhất khi dùng ngay hoặc thêm 1 ít đá. Bạn có thể cảm nhận được độ tươi của cà phê với vị chua tự nhiên của trái cây, đôi khi là mùi cam, quít hoặc mùi trái dâu rừng. Rất thú vị phải không nào.\r\n\r\nGọi cho mình một ly Cold Brew ngay để tự cảm nhận bạn nhé!', 'Cà Phê', 0),
('pro11', 'Cold Brew Phúc Bồn Tử', 50000, 10, 20000, '../IMAGE/ColdBrewPhucBonTu.jpg', 'Cold Brew Phúc Bồn Tử – Sự sáng tạo đầy cảm hứng', 'Cold brew Phúc bồn tử là kết quả của sự kết hợp giữa cà phê pha lạnh đăng đắng, ngọt dịu cùng với hương vị chua nhẹ của phúc bồn tử tự nhiên – Một trải nghiệm khó quên của vị giác.\r\n\r\nNhững năm trở lại đây, cà phê pha lạnh Cold Brew đã trở thành một xu hướng thưởng thức mới đối với các tín đồ cà phê Việt Nam, đang dần trở nên phổ biến rộng rãi, được giới văn phòng và các bạn trẻ vô cùng yêu thích.\r\n\r\nĐược ủ và phục vụ mỗi ngày từ 100% hạt Arabica Cầu Đất. Cách pha chế Cold Brew Phúc Bồn Tử tưởng chừng như đơn giản nhưng thực chất lại đòi hỏi rất nhiều sự tinh tế, cẩn trọng của người Barista trong từng khâu thực hiện.\r\n\r\nNgoài mất 24 tiếng để ngâm ủ cà phê trong nước lạnh như Cold Brew Truyền thống thì việc kết hợp thêm trái phúc bồn tử đã làm dậy lên hương vị trái cây tự nhiên vốn sẵn có trong hạt cà phê, hòa quyện thêm vị đăng đắng, ngọt dịu nhẹ nhàng của Cold Brew để mang đến một cách thưởng thức cà phê hoàn toàn mới, vừa thơm lừng hương cà phê quen thuộc, vừa nhẹ nhàng và thanh mát bởi hương trái cây đầy thú vị.\r\n\r\nMột sáng tạo đầy cảm hứng đúng không nào. Còn chờ gì mà tự mình trải nghiệm ngay một ly Cold Brew Phúc Bồn Tử thơm ngon ngay hôm nay!', 'Cà Phê', 0),
('pro12', 'Cold Brew Sữa Tươi', 45000, 10, 18000, '../IMAGE/ColdBrewSuaTuoi.jpg', 'Cold Brew Sữa Tươi – Hương vị nhẹ nhàng, chiều lòng hội sành uống', 'Mang trên mình một diện mạo xịn sò, cùng với hương vị không quá đậm đắng và cực kì dễ uống, bởi sự kết hợp đầy sáng tạo của Cold Brew và lớp sữa tươi thơm béo.\r\n\r\nNhững năm trở lại đây, cà phê pha lạnh Cold Brew đã trở thành một xu hướng thưởng thức mới đối với các tín đồ cà phê Việt Nam, đang dần trở nên phổ biến rộng rãi, được giới văn phòng và các bạn trẻ vô cùng yêu thích.\r\n\r\nĐược ủ và phục vụ mỗi ngày từ 100% hạt Arabica Cầu Đất. Cách pha chế Cold Brew Sữa Tươi tưởng chừng như đơn giản nhưng thực chất lại đòi hỏi rất nhiều sự tinh tế, cẩn trọng của người Barista trong từng khâu thực hiện.\r\n\r\nNgoài mất 24 tiếng để ngâm ủ cà phê trong nước lạnh như Cold Brew Truyền thống, việc kết hợp thêm sữa tươi đã tạo nên sự thanh mát và cân bằng với hương vị cà phê nguyên bản 100% Arabica Cầu Đất cùng sữa tươi thơm béo cho từng ngụm tròn vị, hấp dẫn.\r\n\r\nĐặc biệt, Cold Brew Sữa Tươi còn rất thích hợp cho những ai không thể uống quá nhiều hoặc chưa từng uống cà phê đấy!\r\n\r\nNào, team đến Sokoshop là chỉ gọi “cà phê” đâu rồi, bạn đã thưởng thức hương vị nhẹ nhàng và đầy khác biệt này chưa?\r\n\r\n', 'Cà Phê', 0),
('pro13', 'Trà Đào Cam Sả - Đá', 45000, 50, 18000, '../IMAGE/TraDaoCamSaDa.jpg', 'Trà đào cam sả - Thức uống nhất định phải thử 1 lần khi đến Sokoshop', 'Có thể bạn chưa biết, Trà Đào Cam Sả chính là một trong những món đồ uống được rất nhiều thực khách gọi mỗi khi ghé thăm Sokoshop. \r\n\r\nHương vị tuy quen mà lạ, tuy lạ mà quen\r\n\r\nKhi sáng chế ra thức uống này, Barista tại Nhà đã để lại dấu ấn riêng rất Việt trong món trà đào vốn đã quen thuộc đối với mọi người bằng một nguyên liệu rất đỗi dân dã - Sả, một loại cây vốn được trồng và sử dụng rộng rãi như là một gia vị thường thấy trong bữa ăn hằng ngày tại các nước châu Á. Sả có hương thơm của chanh, tính ấm, kết hợp với tính hàn của Cam vàng Mỹ, tạo nên sự kết hợp cân bằng, vừa mang dấu ấn riêng của Việt Nam, vừa có sự pha trộn phương Tây trong ly Trà đào Cam Sả Sokoshop. Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này. \r\n\r\nTrà đào cam sả - Bổ sung thêm C, Tăng cường sức đề kháng\r\n\r\nKhông chỉ hương vị thơm ngon, Trà đào cam sả còn có các tác dụng tuyệt vời cho cơ thể. Có thể kể đến như:\r\n\r\nChống oxy hóa: Trong trà đào có chất chống oxy hóa mạnh mẽ và các hợp chất có thể ngăn ngừa quá trình lão hóa của da. \r\n\r\nTăng cường hệ miễn dịch: Chất chống oxy hóa có trong sả và cam còn góp phần nâng cao hệ thống miễn dịch, làm giảm căng thẳng và mệt mỏi. Một ly trà đào mỗi ngày sẽ bổ sung lượng lớn vitamin C giúp cơ thể \r\n\r\nGiảm cân: Tin vui cho bạn là trà đào có thể hỗ trợ đốt cháy chất béo góp phần và quá trình giảm cân hiệu quả. Vừa là thức uống ngon miệng, thời thượng lại vừa có thể giảm béo thì quả là tuyệt vời .\r\n\r\nĐể hiểu vì sao mỗi ngày có rất nhiều ly Trà Đào Cam Sả được Sokoshop trao đến tay khách hàng, order một ly Trà đào cam sả \"trứ danh\" để cảm nhận, bạn nhé!', 'Trà Trái Cây - Trà Sữa', 1),
('pro14', 'Trà Hạt Sen - Nóng', 52000, 15, 25000, '../IMAGE/TraHatSenNong.jpg', 'Trà hạt sen – Sự tinh tế của những điều đơn giản', 'Nền trà oolong hảo hạng kết hợp cùng hạt sen tươi, bùi bùi thơm ngon.\r\n\r\nThức uống gây thương nhớ tại Sokoshop có gì đặc biệt?\r\n\r\nSự kết hợp tinh tế của những nguyên liệu giản đơn \r\n\r\nSự kết hợp của Trà Oolong thanh mát với hương thơm nhẹ nhàng cùng vị nồng hậu của Hạt sen tươi mềm có vị ngọt, bùi. Đặc biệt, lớp kem sữa phô mai được phủ lên bề mặt ly sẽ cho bạn một trải nghiệm cân bằng hơn về hương vị.\r\n\r\nHình thức cực kỳ bắt mắt\r\n\r\nMột ly trà hạt sen chuẩn Soko, bạn có thể nhìn thấy rõ ràng 3 lớp riêng biệt. Lớp đầu tiên là lớp “milk foam” béo ngậy, lớp ở giữa là trà oolong màu vàng sáng và lắng đọng ở lớp đáy là những “hạt ngọc” sen vàng.\r\n\r\nTrà hạt sen bồi bổ sức khoẻ:\r\n\r\nTrà Oolong - thảo dược quý giúp bạn bồi bổ sức khoẻ: Trong trà ô long có chứa rất nhiều vitamin, khoáng chất và những chất chống oxy hóa rất tốt. \r\n\r\n Hạt sen - cung cấp một lượng lớn gluxit, lipit, canxi, chất xơ và các vitamin mang đến nhiều lợi ích ch người dùng từ tác dụng chống viêm, giúp an thần, đến công dụng đẹp da, chống lão hoá, điều hoà cholesterol và đường huyết. \r\n\r\nMột loại thức uống phù hợp cho cả buổi sớm ban mai hay chiều tối với nhiều công dụng tuyệt vời chơ sức khoẻ, bạn đã thử chưa?', 'Trà Trái Cây - Trà Sữa', 0),
('pro15', 'Trà Phúc Bồn Tử', 50000, 20, 20000, '../IMAGE/TraPhucBonTu.jpg', 'Trà Phúc Bồn Tử - Sự kết hợp đầy hoàn hảo giữa thanh mát và bổ dưỡng', 'Bạn đang cần một thức uống giàu Vitamin C để tăng cường đề kháng & bảo vệ sức khỏe? Trà phúc bồn tử Sokoshop thanh mát, bổ dưỡng chính là lựa chọn hoàn hảo dành cho bạn.\r\n\r\nMón trà phúc bồn tử với 2 nguyên liệu chính: quả phúc bồn tử tươi và trà oolong hảo hạng. Phúc bồn tử hay còn gọi là quả mâm xôi là một trong những loại quả rất được ưa chuộng bởi không những chỉ trông thôi đã muốn ăn ngay, mà bản thân nó còn mang lại nhiều giá trị sức khỏe đáng kinh ngạc. Quả Phúc Bồn Tử hoàn toàn tự nhiên, được các barista Nhà kết hợp một cách đầy tinh tế cùng trà Oolong hảo hạng và cam vàng tạo ra một dư vị hoàn toàn tươi mới. Mát lạnh ngay từ ngụm đầu tiên, đọng lại cuối cùng là hương vị trà thơm lừng và vị ngọt thanh, chua dịu khó quên của quả phúc bồn tử tươi. \r\n\r\nPhúc bồn tử được xem là một trong những “siêu thực phẩm” sở hữu nguồn dinh dưỡng dồi dào, bằng chứng là Đông y coi phúc bồn tử là một loại “thực dược lưỡng dụng” nghĩa là vừa dùng làm thực phẩm, vừa có thể làm thảo dược trị bệnh. Cùng Sokoshop điểm qua những công dụng tuyệt vời từ thành phần chính của ly trà phúc bồn tử Sokoshop nhé:\r\n\r\n- Cung cấp vitamin C, K & Mangan cho cơ thể: Những dưỡng chất này đóng vai trò trong việc tăng cường sức đề kháng cho cơ thể, chống lại các bệnh nhiễm trùng, là tác nhân oxy hóa mạnh mẽ ngăn chặn sự xâm nhận của các mầm bệnh đến từ môi trường ngoài, phòng ngừa chứng loãng xương, giảm động kinh và kiểm soát lượng đường trong máu.\r\n\r\n- Quả phúc bồn tử giúp não khỏe mạnh: Ăn những loại trái cây mọng nước như quả quả phúc bồn tử có thể cải thiện sức khỏe của não và giúp ngăn ngừa sự mất trí nhớ do lão hóa.\r\n\r\n- Giúp tăng cường hệ tiêu hóa: Tác dụng của phúc bồn tử có thể giúp bảo vệ màng tế bào nhờ đặc tính chống viêm. Bên cạnh đó, loại quả này cũng cố hệ thống miễn dịch và hỗ trợ tiêu hóa. \r\n\r\nGọi ngay một ly phúc bồn tử để chiêu đãi bản thân ngay nào!', 'Trà Trái Cây - Trà Sữa', 0),
('pro16', 'Trà Đen Macchiato', 50000, 20, 20000, '../IMAGE/TraDenMacchiato.jpg', 'Trà đen Macchiato – Chuẩn vị thơm ngon', 'Trà đen được ủ mới mỗi ngày, giữ nguyên được vị chát mạnh mẽ đặc trưng của lá trà, phủ bên trên là lớp Macchiato \"homemade\" bồng bềnh quyến rũ vị phô mai mặn mặn mà béo béo.\r\n\r\nTrà đen Macchiato là một trong những thức uống được các bạn trẻ rất yêu thích của Sokoshop. Nếu bạn nào đã thử qua, chắc chắn sẽ phải siêu lòng ngay bởi sự hòa quyện giữa vị đắng vừa phải của trà, nhấp từng ngụm bạn sẽ cảm nhận vị ngon khó cưỡng của lớp kem béo ngậy của Macchiato.\r\n\r\nUống Trà Đen Macchiato như thế nào mới đúng cách?\r\n\r\n1 - Giữ nguyên nắp và uống.\r\n\r\n2 - Tháo nắp ra để lớp sữa chạm vào môi và ngửi được hương thơm.\r\n\r\n3 - Lắc lên trước để trà và sữa quyện vào nhau.\r\n\r\nTuy nhiên, cách uống ngon nhất vẫn là cách bạn chọn! Bạn thường thưởng thức trà đen theo cách nào, chia sẻ với Sokoshop với nhé!', 'Trà Trái Cây - Trà Sữa', 0),
('pro17', 'Hồng Trà Sữa Trân Châu', 55000, 50, 25000, '../IMAGE/HongTraSuaTranChau.jpg', 'Ngày ngọt ngào hơn khi có Hồng Trà sữa Trân châu', 'Nằm trong bộ sưu tập Trà sữa Nhà đúng gu, Hồng Trà sữa Trân châu là một mảnh ghép được tạo ra để đáp ứng Gu ngọt ngào của các tín đồ trà sữa.\r\n\r\nHồng Trà sữa Trân châu chuẩn gu ngọt ngào: Hồng trà nguyên lá, sữa thơm ngậy được cân chỉnh với tỉ lệ hoàn hảo, cùng trân châu trắng dai giòn có sẵn để bạn tận hưởng từng ngụm trà sữa ngọt ngào thơm ngậy thiệt đã.\r\n\r\nSokoshop tin rằng, khi bạn thưởng thức đúng hương vị trà sữa mà mình thích cũng là cách thêm chút ngọt ngào cho ngày mới và tận hưởng khoảnh khắc tuyệt vời của cuộc sống.\r\n\r\nVì Hồng trà là nguyên liệu chính làm nên thức uống thơm ngon này nên khi uống cũng mang đến những lợi ích tuyệt vời cho sức khỏe:\r\n\r\n- Giúp tập trung tinh thần, tăng cường trí nhớ. Hợp chất Polyphenol trong hồng còn giúp chắc khỏe xương, ngăn ngừa bệnh loãng xương ở nữ giới.\r\n\r\n- Theo Đông y Trung Quốc, Hồng trà tốt cho hệ tiêu hóa, lợi tiểu… Ngoài ra, trong Hồng trà còn dồi dào Flavonoid có tác dụng kháng acid, tiêu diệt các gốc tự do giúp ngăn ngừa ung thư và các bệnh tiêm mạch.\r\n\r\nGọi cho mình một Hồng Trà sữa Trân châu Sokoshop để tự thưởng cho bản thân đi nào!', 'Trà Trái Cây - Trà Sữa', 1),
('pro18', 'Trà Sữa Oolong Nướng Trân Châu', 55000, 40, 25000, '../IMAGE/TraSuaOolongNuongTranChau.jpg', 'Trà sữa Oolong nướng Trân Châu – Chuẩn gu đậm đà, uống là mê', 'Nằm trong bộ sưu tập Trà sữa Soko đúng gu, Trà sữa Oolong nướng trân châu là một mảnh ghép được tạo ra để đáp ứng gu đậm đà của các tín đồ trà sữa.\r\n\r\nTrà sữa Oolong nướng mang hương vị chân ái đúng gu đậm đà với trà Oolong được “sao” (nướng) lâu hơn cho hương vị đậm đà, hòa quyện với sữa thơm béo mang đến cảm giác mát lạnh, lưu luyến vị trà sữa đậm đà nơi vòm họng, lại còn có trân châu giòn giòn vui miệng - 1 sự kết hợp hoàn hảo!\r\n\r\nSokoshop tin rằng, khi bạn thưởng thức đúng hương vị trà sữa mà mình thích cũng là cách tận hưởng khoảng khắc tuyệt vời của cuộc sống.\r\n\r\nVì Oolong là nguyên liệu chính làm nên thức uống “vạn người mê” này nên khi uống cũng mang đến những lợi ích tuyệt vời cho sức khỏe:\r\n\r\n- Giúp ngăn ngừa tiểu đường, tốt cho hệ tim mạch, hỗ trợ trong việc giảm cân ,…\r\n\r\n- Trà Oolong giúp tăng sức đề kháng, giữ cơ thể khỏe mạnh, tinh thần sảng khoái.\r\n\r\n-   Trà Oolong cũng giúp làm dịu dạ dày hiệu quả.\r\n\r\nGọi ngay một ly Trà sữa Oolong nướng thêm Trân châu thôi nào!', 'Trà Trái Cây - Trà Sữa', 1),
('pro19', 'Trà Sữa Mắc Ca Trân Châu', 50000, 30, 20000, '../IMAGE/TraSuaMacCaTranChau.jpg', 'Trà sữa mắc ca trân châu trắng – Làn gió mới của các tín đồ trà sữa', 'Trà sữa mắc ca trân châu trắng là sự kết hợp giữa nền trà Oolong hảo hạng thơm lừng, cùng sữa hạt mắc ca bổ dưỡng ngọt dịu ít béo, đặc biệt là topping trân châu trắng dai giòn hấp dẫn.\r\n\r\nĐây là một \"làn gió mới\" mà Sokoshop mang đến cho bạn hương vị mới, trải nghiệm mới cho để bạn đổi vị tươi mới hơn và thú vị hơn. \r\n\r\nSokoshop tin rằng, mỗi ngày sẽ là điều tươi mới hơn với sữa hạt mắc ca thơm ngon, bổ dưỡng quyện cùng nền trà oolong cho vị cân bằng, ngọt dịu đi kèm cùng trân châu trắng giòn dai mang lại cảm giác “đã” trong từng ngụm Trà sữa Mắc ca trân châu trắng.\r\n\r\nĐặt một ly và cho Sokoshop biết cảm nhận nhé!', 'Trà Trái Cây - Trà Sữa', 0),
('pro20', 'Hồng Trà Latte Macchiato', 55000, 20, 25000, '../IMAGE/HongTraLatteMacchiato.jpg', 'Hồng trà Latte Macchiato – Đỉnh cao của sự tinh tế', 'Nằm trong bộ sưu tập Trà sữa Soko đúng gu, Hồng trà Latte Macchiato là một mảnh ghép được tạo ra để đáp ứng Gu tinh tế của các tín đồ trà sữa.\r\n\r\nHồng trà Latte Macchiato chính là sự kết hợp hoàn hảo bởi hồng trà dịu nhẹ và sữa tươi, nhấn nhá thêm lớp macchiato trứ danh của Sokoshop mang đến cho bạn hương vị trà sữa đúng gu tinh tế và healthy.\r\n\r\nSokoshop tin rằng, khi bạn thưởng thức đúng hương vị trà sữa mà mình thích cũng là cách bạn đang chiều chuộng bản thân và tận hưởng khoảnh khắc tuyệt vời của cuộc sống.\r\n\r\nVì Hồng trà là nguyên liệu chính làm nên thức uống tinh tế này nên khi uống cũng mang đến những lợi ích tuyệt vời cho sức khỏe:\r\n\r\n- Giúp tập trung tinh thần, tăng cường trí nhớ. Hợp chất Polyphenol trong hồng còn giúp chắc khỏe xương, ngăn ngừa bệnh loãng xương ở nữ giới.\r\n\r\n- Theo Đông y Trung Quốc, Hồng trà tốt cho hệ tiêu hóa, lợi tiểu… Ngoài ra, trong Hồng trà còn dồi dào Flavonoid có tác dụng kháng acid, tiêu diệt các gốc tự do giúp ngăn ngừa ung thư và các bệnh tiêm mạch.\r\n\r\nNếu bạn thuộc team trà sữa nhưng sợ bị tăng cân thì Hồng Trà Latte Macchiato Sokoshop chính là chân ái của bạn đấy nhé!', 'Trà Trái Cây - Trà Sữa', 1),
('pro21', 'Trà Long Nhãn Hạt Chia', 45000, 20, 18000, '../IMAGE/TraLongNhanHatChia.jpg', 'Trà long nhãn hạt chia – Nguồn cảm hứng từ thức quà của vùng nhiệt đới', 'Với nguồn cảm hứng chính từ loại trái cây quen thuộc của vùng nhiệt đới – quả nhãn, các Barista Soko đã khéo léo kết hợp cùng trà oolong và hạt chia để mang đến Trà long nhãn hạt chia thơm ngon, đầy bổ dưỡng.\r\n\r\nMón trà với 3 nguyên liệu chính: Nhãn, trà oolong & hạt chia. \r\n\r\nNền trà oolong hảo hạng kết hợp với vị nhãn vạn người mê. Vị nhãn ngọt dịu, tươi mát đặc trưng quyện cùng trà và hạt chia. Không gì tuyệt vời hơn bằng việc giải nhiệt kịp thời mỗi khi tiết trời oi bức cùng một ly trà long nhãn hạt chia mát lạnh, bổ dưỡng. \r\n\r\nTrà long nhãn hạt chia không chỉ được yêu thích bởi hương vị ngọt mà còn bởi những giá trị dinh dưỡng đối với sức khỏe mà thức uống này mang lại:\r\n\r\n- Quả nhãn bổ sung nguồn năng lượng dồi dào, cung cấp Vitamin C và khả năng cải thiện tuần hoàn máu.\r\n\r\n- Hạt chia được biết đến như một loại hạt rất tốt cho cơ thể với nhiều công dụng tuyệt vời như: giàu chất chống oxy hoá, hàm lượng chất xơ & protein cao giúp giảm cân, góp phần giảm nguy cơ mắc bệnh tim mạch.  Bên cạnh đó hạt chia còn là nguồn cung câp lành mạnh cho xương. \r\n\r\n- Trà Oolong – thảo dược quý giúp bạn bồi bổ sức khoẻ: Trong trà ô long có chứa rất nhiều vitamin, khoáng chất và những chất chống oxy hóa rất tốt.\r\n\r\nMột ly trà long nhãn hạt chia không chỉ thơm ngon mà còn mang đến nhiều lợi ích cho sức khoẻ, còn chần chừ gì mà không order ngay cho mình một ly bạn nhỉ?', 'Trà Trái Cây - Trà Sữa', 0),
('pro22', 'Chocolate Đá Xay', 59000, 40, 30000, '../IMAGE/ChocolateDaXay.jpg', 'Chocolate đá xay – Thức uống cho tín đồ hảo ngọt​', 'Hương vị chocolate quyến rũ, thức uống được sinh ra dành cho các tín đồ hảo ngọt.\r\n\r\nSữa và kem tươi béo ngọt được “cá tính hoá” bởi vị chocolate đăng đắng. Giống như các thức uống khác của dòng đá xay như Cà phê đá xay, Matcha đá xay,… một ly Chocolate đá xay đạt chuẩn Barista Soko phải: \r\n\r\nKhi uống cảm nhận được hương thơm, vị đăng đắng đặc trưng của chocolate, thơm béo của sữa.\r\n\r\nĐá viên được xay nhuyễn mịn, không bị lẫn các viên đá còn to.\r\n\r\nLớp kem tươi xốp, béo và được xịt vừa đủ lên trên ly.​\r\n\r\nChocolate là một loại thực phẩm có nhiều công dụng hữu ích, làm hưng phấn tâm trạng do có caffeine, tyrosine và tryptophan. Trong các loại chocolate, chocolate đen được Barista Soko dùng trong món chocolate đá xay có hàm lượng ca cao cao cùng với chất chống oxy hóa, ít chất béo nên có lợi cho sức khỏe hơn. Chỉ một lượng nhỏ chocolate cũng giúp bạn tràn đầy năng lượng? Không chỉ thế, chocolate còn được các chuyên gia sức khoẻ công nhận do có nhiều lợi ích có thể kể đến như:\r\n\r\nCải thiện sức khỏe tim mạch: Chocolate có thể giúp giảm huyết áo và chống viêm. Theo các nghiên cứu, chocolate có hàm lượng flavonoid cao. Flavonoid có thể kích thích cơ thể tạo ra nhiều oxit nitric hơn, giúp mở rộng và “thư giãn” mạch máu, do đó làm giảm huyết áp.\r\n\r\nGiống như trà xanh, chocolate cũng có epicatechin, giúp não chống lại quá trình hình thành các protein kết dích hay các mảng amyloid giúp hạn chế nguy cơ gây ra bệnh Alzheimer.\r\n\r\nCó hiểu lầm cho rằng dùng chocolate sẽ gây tăng cân hay các tình trạng sức khỏe khác. Tuy nhiên, theo các nghiên cứu, chỉ cần bạn dùng một lượng nhỏ sẽ không có tác hại xấu đến cơ thể.\r\n\r\nCòn có lựa chọn nào tốt hơn cho tinh thần hơn là một ly chocolate đá xay. Order ngay!', 'Đá Xay - Choco - Matcha', 1),
('pro23', 'Phúc Bồn Tử Cam Đá Xay', 59000, 30, 30000, '../IMAGE/PhucBonTuCamDaXay.jpg', 'Phúc bồn tử cam đá xay - Tê tái đầy thú vị', '1 cú “twist” ngoạn mục trong hương vị của Đá Xay mát lạnh. Sự kết hợp phá cách đầy thú vị dành cho “team đá xay” và “team trái cây”\r\n\r\nSau nhiều năm làm vai phụ để nâng tầm cho hương vị khác, giờ đây CAM VÀNG TƯƠI 100% đã trở thành nhân vật chính trong bộ sưu tập Vitamin C dành cho team yêu bản thân. Ra đời trong trong cái nóng bức của mùa hè, Phúc bồn tử cam đá xay với vị chua chua ngọt ngọt của cam kết hợp với vị ngọt dịu nhẹ từ quả phúc bồn tử 100% tự nhiên đã tạo nên một thức uống tuyệt ngon để giải nhiệt. Cùng với sự phân tầng đẹp mắt của 3 mảng màu chiết xuất từ trái cây 100% tự nhiên: Trắng - Vàng - Đỏ, để kích thích sự tò mò, mang đến sự the mát và bổ dưỡng tuyệt vời cho team thích đá xay lẫn trái cây.\r\n\r\nThức uống để bạn nạp C 100% tự nhiên\r\n\r\nCả cam vàng và việt quất đều nổi tiếng bởi hàm lượng Vitamin C mà 2 loại quả này có. Cùng Soko lướt qua những công dụng mà Vitamin C mang đến cho cơ thể.\r\n\r\n- Giảm nguy cơ mắc các bệnh mãn tính: Vitamin C được xem như một trong những chất chống oxy hoá mạnh, giúp tăng cường hệ miễn dịch, bảo vệ cơ thể \r\n\r\n- Phòng bệnh tim mạch: Vitamin C giúp cơ thể giảm huyết áp, hỗ trợ các mạch máu hoạt động trơn tru hơn. \r\n\r\n- Ngăn ngừa tình trạng thiếu sắt: Vitamin C giúp cơ thể trong quá trình hấp thụ Sắt – một chất dinh dưỡng quan trọng, đảm nhận nhiều chức năng trong cơ thể.\r\n\r\nCần một hương vị thanh mát, kích thích vị giác đầy thú vị ngay từ lần đầu thưởng thức. Gọi ngay 1 ly phúc bồn tử cam đá xay để thưởng thức.', 'Đá Xay - Choco - Matcha', 0),
('pro24', 'Chanh Sả Đá Xay', 49000, 30, 20000, '../IMAGE/ChanhSaDaXay.jpg', 'Chanh sả đá xay – Thức uống thanh mát, giải nhiệt', 'Nước cốt sả (sả ngâm) xay cùng với chanh tươi, thêm vào chút đường tạo nên thức ống với hương vị thanh chua, ngọt ngọt, thơm nhẹ thoảng nhẹ mùi sả. Tuy thành phần đơn giản nhưng để có một ly chanh sả đá xay đúng điệu cùng cần tay nghề khéo léo của Barista Soko từ sự kết hợp giữa các thành phần đến độ nhuyễn mịn của đá xay. \r\n\r\nTuy là những nguyên liệu đơn giản nhưng sả và chanh lại có những công dụng cực kỳ tốt đối với sức khoẻ:\r\n\r\nSả rất tốt cho hệ tiêu hoá, hỗ trợ tốt cho hệ thần kinh, có tính kháng viêm và đăc biệt tốt cho cho người muốn giảm cân do sả có tác dụng đốt cháy mỡ thừa, làm thúc đẩy quá trình trao đổi giúp máu lưu thông tốt hơn.\r\n\r\nTrong khi đó Chanh lại là loại quả cung cấp rất nhiều vitamin C, chất xơ và các hợp chất thực vật có lợi khác nhau. Những chất dinh dưỡng này đem lại một số lợi ích cho sức khỏe. Trên thực tế, chanh có thể hỗ trợ sức khỏe tim mạch, kiểm soát cân nặng và sức khỏe hệ tiêu hóa.\r\n\r\nGọi một ly chanh sả đá xay để giải nhiệt ngay thôi nào!', 'Đá Xay - Choco - Matcha', 0),
('pro25', 'Đào Việt Quất Đá Xay', 59000, 25, 30000, '../IMAGE/DaoVietQuatDaXay.jpg', 'Đào việt quất đá xay –  Sự pha trộn hoàn hảo giữa đào và việt quất', 'Một trong những món đá xay phá cách được yêu thích nhất tại Sokoshop\r\n\r\nLà phiên bản “upgrade” từ ly trà đào quen thuộc của nhà, tuy là “em út” trong giá đình đá xay nhưng món đào việt quất đá xay lại nhanh chóng quen mặt, sau thời gian thử thách đã chính thức từ thức uống theo mùa trở thành món uống trên menu chính thức của Soko. Được khoác lên mình ngoại hình xịn sò, mang đến sự phấn khích và tươi mát ngay từ cái nhìn đầu tiên, ở giữa là vị đào huyền thoại ngọt thanh, lớp việt quất chua ngọt vui miệng ở tầng cuối, đặc biệt kéo theo lớp kem bồng bềnh béo ngậy trên cùng nữa mang đến hương vị kích thích vị giác đầy lôi cuốn và khoan khoái ngay từ ngụm đầu tiên.\r\n\r\nNgon miệng, ngon mắt lại còn chứa nhiều vitamin\r\n\r\n- Quả đào chứa nguồn vitamin dồi dào, đặc biệt là những loại vitamin thiết yếu. Các loại vitamin và khoáng chất có thể kể đến như: Vitamin K, canxi, phốt pho, đồng, kẽm. Các vitamin & khoáng chất này có nhiều công dụng tốt cho sức khỏe, đặc biệt là khả năng cải thiện thị lực, các vấn đề về xương và thần kinh.\r\n\r\n- Mứt việt quất chứa vitamin C, Vitamin K, Canxi, magie, kali… giúp xương chắc khoẻ, giảm nguy cơ mắc bệnh tiểu đường, tăng cường hệ tiêu hoá và giúp bạn kiểm soát cân nặng nhờ vào chất xơ có trong thành phần. \r\n\r\nĐặc biệt cả 2 loại quả đều có công dụng giúp da tránh khỏi sự lão hoá. \r\n\r\nNắng nóng, sức lực làm việc bỗng nhiên bị “bốc hơi”, tự nhiên thèm một thứ gì đó hạ hỏa và lên tinh thần ngay lúc này, order một ly đào việt quất đá xay và thưởng thức nhé!', 'Đá Xay - Choco - Matcha', 1),
('pro26', 'Matcha Đá Xay', 59000, 50, 30000, '../IMAGE/MatchaDaXay.jpg', 'Matcha Đá Xay –Thức uống gây thương nhớ vô cùng', 'Món ruột của Fan trà xanh ở Sokoshop có gì?\r\n\r\nMatcha đá xay (còn gọi là trà xanh đá xay hay matcha ice blended) là thức uống được các Barista Soko đưa vào menu ngay từ những ngày đầu. Mang đủ các đặc trưng của dòng đá xay, sự mát lạnh, lớp kem béo hấp dẫn, và cộng thêm hương vị matcha đặc biệt được tuyển chọn với chất lượng và hương vị hấp dẫn.  Matcha thanh, nhẫn, và đắng nhẹ được nhân đôi sảng khoái khi uống lạnh. Nhấn nhá thêm những nét bùi béo của kem và sữa. Dù không mới nhưng khả năng gây thương nhớ vẫn như những ngày đầu.\r\n\r\nMatcha chứa chất chống oxy hóa giúp đẩy lùi các tác nhân gây ung thư… Ngoài ra, khi thưởng thức trà xanh còn giúp cho bạn tỉnh táo, giảm căng thẳng và mệt mỏi vì trong trà xanh có chứa caffeine. Bột trà xanh còn chứa hàm lượng polyphenol giúp ngăn ngừa lão hóa, làm đẹp da, sáng da và trị mụn. Thêm vào đó, matcha sẽ giúp cơ thể đào thải được độc tố, thanh nhiệt. Từ đó giúp các cơ quan trong cơ thể hoạt động một cách tốt hơn.\r\n\r\nNếu chưa biết uống gì, thì mình order món ruột matcha đá xay mát lạnh nhé!', 'Đá Xay - Choco - Matcha', 1),
('pro27', 'Sinh Tố Việt Quất', 59000, 30, 30000, '../IMAGE/SinhToVietQuat.jpg', 'Sinh tố Việt quất – Uống ngon, uống “đẹp”', 'Sự phối hợp hợp tinh tế của Barista Soko\r\n\r\nSinh tố là tên gọi chung của những món trái cây xay. Ở Đây chúng ta có sinh tố việt quất với thành phần chính là mứt việt quất, sữa chua và Foam cheese. Mứt Việt Quất chua thanh, ngòn ngọt, phối hợp nhịp nhàng với dòng sữa chua bổ dưỡng, thêm vào đó là vị béo của Foam cheese được Barista Soko phối hợp tinh tế. Tất cả tạo món sinh tố thơm ngon mà cả đầu lưỡi và làn da đều thích. \r\n\r\nVới thành phần chính là mứt việt quất - loại trái cây được nhiều yêu thích vì công dụng cho sức khoẻ và đặc biệt làn da. Sinh tố việt quất có nhiều lợi ích có thể kể đến như:\r\n\r\n- Tốt cho làn da: Vitamin C trong việt quất được xem như là một dưỡng chất cần thiết giúp da tránh khỏi sự lão hóa da dưới tác động của ánh nắng mặt trời, ô nhiễm và khói bụi. \r\n\r\n- Những lợi ích đáng kể đối với sức khoẻ: Ngoài vitamin C, trong việt quất còn chứa các loại khoáng chất khác có ích như Vitamin K, Canxi, magie, kali… giúp xương chắc khoẻ, giảm nguy cơ mắc bệnh tiểu đường, tăng cường hệ tiêu hoá và giúp bạn kiểm soát cân nặng nhờ vào chất xơ có trong thành phần.\r\n\r\nTại Sokoshop, mỗi thức uống ra đời không chỉ đảm bảo tiêu chí ngon miệng mà còn quan tâm đến công dụng đối với sức khoẻ.\r\n\r\n﻿﻿﻿Gọi ngay một ly sinh tố việt quất làm quà cho làn da bạn nhé!', 'Đá Xay - Choco - Matcha', 0),
('pro28', 'Cà Phê Peak Flavor Hương Thơm Đỉnh Cao (350G)', 90000, 20, 40000, '../IMAGE/PeakFlavor.jpg', 'Cà phê rang xay Peak Flavor - Hương thơm đỉnh cao', 'Sokoshop tin rằng, mỗi hạt cà phê đều mang một cá tính riêng biệt, không thể nào hòa lẫn. \r\n\r\n\"Cá tính\" rất riêng ấy được tạo nên bởi vùng thổ nhưỡng mà cây được vun trồng, bởi bàn tay người nông hộ đã thấu hiểu tường tận đất đai nơi này.\r\n\r\nTừng nốt hương mang vị mặn, đắng, chát, chua thanh hay ngọt ngào,... tất cả hoà quyện tạo thành những bản sắc khác biệt trong mỗi ngụm cà phê.\r\n\r\nBằng việc cho ra đời sản phẩm Cà phê rang xay Peak Flavor – Hương thơm đỉnh cao lưu giữ trọn vẹn hương thơm tinh tế đặc trưng của cà phê Arabica Cầu Đất và Robusta Đăk Nông. Với sự hòa trộn nhiều cung bậc giữa hương và vị, Cà phê rang xay Sokoshop sẽ mang đến cho bạn một ngày mới tràn đầy cảm hứng.\r\n\r\n*Sản phẩm thích hợp để uống cà phê sữa nóng/đá.', 'Thưởng Thức Tại Nhà', 0),
('pro29', 'Cà Phê Rich Finish Gu Đậm Tinh Tế (350G)', 90000, 20, 40000, '../IMAGE/RichFinish.jpg', 'Cà phê rang xay Rich Finish - Gu đậm tinh tế', 'Sokoshop tin rằng, mỗi hạt cà phê đều mang một cá tính riêng biệt, không thể nào hòa lẫn. \r\n\r\n\"Cá tính\" rất riêng ấy được tạo nên bởi vùng thổ nhưỡng mà cây được vun trồng, bởi bàn tay người nông hộ đã thấu hiểu tường tận đất đai nơi này.\r\n\r\nTừng nốt hương mang vị mặn, đắng, chát, chua thanh hay ngọt ngào,... tất cả hoà quyện tạo thành những bản sắc khác biệt trong mỗi ngụm cà phê.\r\n\r\nBằng việc cho ra đời sản phẩm Cà phê rang xay Rich Finish – Công thức cà phê được phối trộn hoàn hảo giữa Robusta và Arabica, Sokoshop hiểu rằng ly cà phê ngon phải đậm đà, rõ vị từ cái chạm đầu tiên đến hậu vị vương vấn. Cà phê rang xay Rich Finish mang đến những ly cà phê đậm, thơm, hương vị tinh tế giúp bạn bắt đầu ngày mới đầy năng lượng.\r\n\r\n*Sản phẩm thích hợp để uống cà phê đen nóng/đá.', 'Thưởng Thức Tại Nhà', 0);
